version: 2

build:
  os: ubuntu-24.04
  tools:
      python: "3"
  jobs:
    post_install:
      - sphinx-apidoc -M -o docs/generated sparsecoding
      - pip install -r requirements.txt

sphinx:
  configuration: docs/conf.py

python:
  install:
      - requirements: docs/requirements.txt