name: static

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  static:
    name: static
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          token: ${{github.token}}

      - name: set up python
        uses: actions/setup-python@v4
        with:
          python-version: 3.11
          token: ${{github.token}}

      - name: install requirements
        run: |
          python -m venv --upgrade-deps .venv
          source .venv/bin/activate
          pip install .[all]

      - name: Get all Python files
        id: list_files
        run: |
          echo "files=$(git ls-files '*.py' '*.pyi' | xargs)" >> $GITHUB_OUTPUT

      - name: analysing code with pyright
        run: |
          source .venv/bin/activate
          files="${{ steps.list_files.outputs.files }}"
          if [ -n "$files" ]; then
            python -m pyright $files
          else
            echo "No Python files found."
          fi
